### ISSUE TITLE
Update .travis.yml to use openjdk8 from openjdk7

### ISSUE THREAD

**Issue by mbernier** [sendgrid/smtpapi-java#51]
#### Issue Summary
We had success with not using the deprecated openjdk7 in our sendgrid/java-http-client repo. I would have made this change: 
```
jdk:
- oraclejdk8
- openjdk8
```
But I am not familiar enough with TravisCI to understand what this is: 
```
matrix:
  include:
    - os: linux
      dist: precise
      jdk: openjdk7
    - os: linux
      jdk: oraclejdk8
```
My guess is that I could just replace `jdk: ` but I would rather someone who knows wtf they are doing to help with this!
